aml-org/amf-metadata

vocabulary/src/main/resources/dialects/canonical_webapi_spec.yaml
vocabulary/src/main/resources/vocabularies/api_binding.yaml

Related PR: https://github.com/aml-org/amf/pull/613

APIMF-2412: updated dialects and vocabularies due to AMF meta-model change

---

exporters/src/main/scala/amf/exporters/CanonicalWebAPISpecDialectExporter.scala
exporters/src/main/scala/amf/exporters/VocabularyExporter.scala
transform/src/main/scala/amf/transform/canonical/CanonicalWebAPISpecTransformer.scala

Related to: https://github.com/aml-org/amf/pull/1021

Changed 'non-inclusive' language

---

transform/dependencies.properties
versions.yaml

- publish 5.0.2
- publish 5.1.0-SNAPSHOT in amf-metadata

back to snapshot versions

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

- add release/* to publish step
- adopt amf-api-contract 5.0.6-RC.0 & amf-rdf 6.0.6-RC.0

publish rc 0

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

- Publish RC.0 for amf-transform and amf-vocabulary artifacts
- Publish snapshots

publish 5.2.0 SNAPSHOT

---

transform/dependencies.properties
versions.yaml

- Publish 2.13 and 28.1
- Publish 2.14.0-SNAPSHOT and 29.1.0-SNAPSHOT

Publish 2.14.0-SNAPSHOT and 29.1.0-SNAPSHOT

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

- Back to SNAPSHOT
- Publish amf-vocabulary 33.0.0-RC.0 and amf-transform 2.17.0-RC.0
- Publish amf-vocabulary 33.0.0 and amf-transform 2.17.0

Publish amf-vocabulary 33.0.0 and amf-transform 2.17.0

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

Publish 5.4.0

---

transform/dependencies.properties
versions.yaml

Publish 5.4.0 dev

---

transform/dependencies.properties
versions.yaml

W-13755654 Hf/5.4.0 1

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

publish 38.0.0

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

W-13183825 Publish 39.0.0

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

W-13925186 Publish 40.0.0 setup

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

W-13925186 Publish 40.0.0

---

transform/dependencies.properties

W-13925189 Rc 41.0.0

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

W-13925189 Publish 41.0.0

---

transform/dependencies.properties
versions.yaml

W-13925166 update metada RCs

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

W-13925191 Publish 42.0.0

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

W-13925192 Publish 43.0.0

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

W-14654425 publish 44.0.0

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

W-13925199 Publish 45.0.0

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

W-14875427 Publish 46.0.0

---

transform/dependencies.properties
vocabulary/src/main/resources/dialects/canonical_webapi_spec.yaml
vocabulary/src/main/resources/vocabularies/api_binding.yaml

- **add new async 2.x interfaces**
- **adopt amf 5.5.0-RC.1**

publish metadata RCs

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

- **Publish 47.0.0-SNAPSHOT**
- **publish 47.0.0-RC.0**
- **add new async 2.x interfaces**
- **adopt amf 5.5.0-RC.1**
- **W-14916894 - Adopt amf 5.5.0-RC.2**
- **adopt amf 5.5.0-RC.3**
- **adopt amf 5.5.0-RC.5**
- **publish vocabulary 47.0.0 and transform 2.31.0**

publish vocabulary 47.0.0 and transform 2.31.0

---

transform/dependencies.properties
versions.yaml

W-15327434 update amf RC version

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

W-15327434 Publish 48.0.0

---

vocabulary/src/main/resources/dialects/canonical_webapi_spec.yaml
vocabulary/src/main/resources/vocabularies/api_binding.yaml

Add changes from binding versioning

W-15643510: Add changes from binding versioning

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

W-15770660 Publish 49.0.0

---

transform/dependencies.properties

W-16224755: update 5.5.4-RC.1

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

W-16224755: Publish 51.0.0

---

exporters/src/test/scala/amf/exporters/VocabularyPropertiesTest.scala
vocabulary/src/main/resources/dialects/canonical_webapi_spec.yaml
vocabulary/src/main/resources/vocabularies/api_contract.yaml

W-17016391: Update test for amf-metadata

---

Jenkinsfile
exporters/src/test/scala/amf/exporters/VocabularyPropertiesTest.scala
transform/dependencies.properties
versions.yaml
vocabulary/src/main/resources/dialects/canonical_webapi_spec.yaml
vocabulary/src/main/resources/vocabularies/api_contract.yaml

W-17007563: Publish 56.0.0

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

W-17312785: Publish 57.0.0 and 2.41.0

---

Jenkinsfile
exporters/src/test/scala/amf/exporters/VocabularyPropertiesTest.scala
transform/dependencies.properties
versions.yaml
vocabulary/src/main/resources/dialects/canonical_webapi_spec.yaml
vocabulary/src/main/resources/vocabularies/aml_doc.yaml
vocabulary/src/main/resources/vocabularies/data_shapes.yaml

W-17312785: Publish 57.0.0

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

W-17312785: Publish 57.0.0 dev

---

Jenkinsfile
transform/dependencies.properties
versions.yaml

W-18217146: publish 58.0.0 and 2.42.0
